//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeriLoyalty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int id { get; set; }
        public string FIO { get; set; }
        public string Tel { get; set; }
        public string Status { get; set; }
        public string Bonus { get; set; }
        public int loyaltyId { get; set; }
    
        public virtual Loyalties Loyalties { get; set; }
    }
}
